SwirlsORS/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BootstrapMVC.Models;
using System.IO;
using BootstrapMVC.Helpers;
using System.Collections;
using System.Xml.Linq;
using System.Threading.Tasks;



namespace BootstrapMVC.Controllers
{
    public class StoresController : Controller
    {

//            currentDomain.UnhandledException+= UnhandledException.currentDomain_UnhandledException;
           

        public delegate int Comparator(Product x, Product y);

        private StoresEntities db = new StoresEntities();

        ObjectLearner oLearner = new ObjectLearner();
       
        

        //// GET: Items 
        //public ActionResult Index()
        //{
        //    var products = db.Products 
        //        .Where(p => p.Name.Contains("Deepa")).ToList();
        //    // .Select(p);
        //    List<Product> prodList = products.ToList();
        //    return View(prodList);

        //    // return View(db.Products.ToList());

        //}
        //[HttpGet][ActionName("Index")]
        ////[ValidateAntiForgeryToken]
        //public ActionResult Search(string searchOption, string searchText)
        //{
        //    //if (int id == 1)
        //    //    sortBy = "Name";
        //    if (searchOption != null && searchText != null)
        //    {
        //        Product prod = new Product();
        //        List<Product> SelectedList = db.Products.ToList();
        //     //   int locateName = db.Products.ToList().IndexOf(prod);
        //        var products = from p in db.Products
        //                       where prod.Name.Contains(searchText)
        //                       select p;

        //        //return RedirectToAction("Index",); 
        //        return View(db.Products.ToList());

        //                   }
        //    else
        //    {
        //        return View(db.Products.ToList());
        //    }

        //}

        static void currentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e) 
        {
            Exception ex = (Exception)e.ExceptionObject;

            // logging and warning messages

//            Console.WriteLine("Runtime terminating: {0}", e.IsTerminating);
       
        }

         [HttpGet] 
        public ActionResult Index(string sortBy, string searchText, int priceMinRange=0, int priceMaxRange=25000)
        {
            AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(currentDomain_UnhandledException);
           // Application.ThreadException += new UnhandledExceptionEventHandler(currentDomain_UnhandledException);
             #region Unhandled Exception Test
            //string testUnhandle = null;
            //testUnhandle.ToString();

            #endregion

            

            #region List to Array
            //List<Product> baseList = db.Products.ToList();
            //// int arraySize= baseList.Count;
            //Product[] productArray = baseList.ToArray();
            //Array productDestinationArray = Array.CreateInstance(typeof(Product), baseList.Count);
            //Array.Copy(productArray, productArray.GetLowerBound(0) + 5
            //    , productDestinationArray, productDestinationArray.GetLowerBound(0), productDestinationArray.GetLowerBound(0) + 25);

            //Array.ConstrainedCopy(productArray, productArray.GetLowerBound(0) + 5
            //  , productDestinationArray, productDestinationArray.GetLowerBound(0), productDestinationArray.GetLowerBound(0) + 5);
             
         

            #endregion

            #region List to XML
            List<Product> xmlList = db.Products.ToList();
            var xmlFromList = new XElement("Products"
                , xmlList.Select(x => new XElement("Product"
                , new  XAttribute("Id", x.ID)
                , new XAttribute("Name", x.Name)
                , new XAttribute("Price", x.Price))));
               
            #endregion
            IQueryable iqueryable;
            oLearner.Equals(oLearner);
            var hashCode= oLearner.GetHashCode();
            var typeCurrentInstance= oLearner.GetType();
            var objStr= oLearner.ToString();

            //FormCollection fc = new FormCollection();
            //fc.Add("oLearner",oLearner.ToString());
           // ArrayList aList = new ArrayList();



             
            Logger.logger.Info("Inside  Store Index Info");
            Logger.logger.Fatal("Inside  Store Index Fatal");
            Logger.logger.Error("Inside  Store Index Error");
            Logger.logger.Debug("Inside  Store Index Debug");
            Logger.logger.Warn("Inside  Store Index Warn");
           
            //string sortBy2= null;
            //if (int id == 1)
            //    sortBy = "Name"; 


            #region Locating Object for an element- IComparable IndexOf has to implement Equals n GetHashCode
            Product prod = new Product();

            prod = db.Products.Find(20);
            int locateName = db.Products.ToList().IndexOf(prod);
            List<Product> productsLambda = db.Products.ToList();
            #endregion





            if (sortBy != null && !"".Equals(sortBy))
            {

                

                PriceComparer pComparer = new PriceComparer();
                NameComparer nComparer = new NameComparer();
                //List<Product> IndexofList = db.Products.ToList();
              



                Product p1; Product p2;
                //Comparator pcomparator = new Comparator(StoresController.compare(p1,p2));

                //test(new Comparator(Compare));
                //test(new Comparator(Compare1));
                //SortedList.Sort(pComparer);
                
                //db.Products.ToList().IndexOf(prod);
                if (sortBy == "ID")
                {
                    List<Product> SortedList = db.Products.ToList();
                    SortedList.Sort();
                    return View(SortedList);
                }
                if (sortBy == "Price")
                {
                    List<Product> SortedList = db.Products.ToList();
                    #region Interface with one method 
                    //SortedList.Sort(pComparer);
                    #endregion
                    #region Anonymous Methods
                    //SortedList.Sort(delegate(Product x, Product y)
                    //                            {
                                                    
                    //                                    if (x.Price > y.Price)
                    //                                         return 1;
                    //                                    else if (x.Price < y.Price)
                    //                                        return -1;
                    //                                    else
                    //                                        return 0;

                    //                            });
                    #endregion
                    #region Named Delegate
                    //SortedList.Sort(Compare);
                    #endregion
                    #region Lambda Expressions
                    SortedList.Sort((p3,p4) => p3.Price.CompareTo(p4.Price));
                    SortedList.OrderByDescending(p => p.Price).ToList();
                    #endregion
                    return View(SortedList);
                }
                else if (sortBy == "Name") 
                {
                    List<Product> SortedList = db.Products.ToList();
                    SortedList.Sort(nComparer);
                    SortedList.Reverse();
                    return View(SortedList);
                }
                else
                {
                    return View(db.Products.ToList());
                }
            }
            else
                {
                    var products = db.Products.ToList();
                    if (searchText != null && !"".Equals(searchText))
                    {
                        products = products
                       .Where(p => p.Name.Contains(searchText) && (p.Price > priceMinRange && p.Price <= priceMaxRange)).ToList();
                        List<Product> prodList = products.ToList();
                        

                        //var productPrice = db.Products.
                        //  Where(p => (p.Price > 0 && p.Price <= 10)).ToList();
                    }
                    else
                    {
                        products = products
                      .Where(p => (p.Price > priceMinRange && p.Price <= priceMaxRange)).ToList();
                        List<Product> prodList = products.ToList();
                        

                    }

                        return View("Index", products);

                }

        }

        [HttpPost] 
        public ActionResult SearchIndex(string sortBy, string searchOption ,string searchText,FormCollection formcol)
         {
             
             //string sortBy2= null;
             //if (int id == 1)
             //    sortBy = "Name";


             if (sortBy != null && !"".Equals(sortBy))
             {

                 Product prod = new Product();


                 prod = db.Products.Find(20);


                 PriceComparer pComparer = new PriceComparer();
                 NameComparer nComparer = new NameComparer();
                 List<Product> IndexofList = db.Products.ToList();
                 int locateName = db.Products.ToList().IndexOf(prod);
                 db.Products.ToList().IndexOf(prod);
                 if (sortBy == "ID")
                 {
                     List<Product> SortedList = db.Products.ToList();
                     SortedList.Sort();
                     return View("Index",SortedList);
                 }
                 if (sortBy == "Price")
                 {

SwirlsORS/Controllers/TitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BootstrapMVC.Models;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using log4net;
using System.Transactions;


namespace BootstrapMVC.Controllers
{
    public class TitlesController : Controller
    {

        private StoresEntities db = new StoresEntities();

        // GET: Titles
        public ActionResult Index()
        {

            var titles = db.Titles.Include(t => t.CATEGORY);
            return View(titles.ToList());

        }

        // GET: Titles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Title title = db.Titles.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }

        // GET: Titles/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.CATEGORies, "ID", "Name");
            return View();
        }

        // POST: Titles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,CategoryID")] Title title)
        {
            using (TransactionScope transactionScope = new TransactionScope())
            {
                try
                {

                    if (ModelState.IsValid)
                    {
                        db.Titles.Add(title);
                        db.SaveChanges();
                        FileStream fs = new FileStream(@"D:\\RE", FileMode.Append);

                    }

                    ViewBag.CategoryID = new SelectList(db.CATEGORies, "ID", "Name", title.CategoryID);
                    transactionScope.Complete();
                    return RedirectToAction("Index");
                }
                catch
                {
                    transactionScope.Dispose();
                }
                finally
                {
                    // transactionScope.Dispose();

                }
                return View(title);

            }
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Name,CategoryID")] Title title)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        db.Titles.Add(title);
        //        db.SaveChanges();
        //        FileStream fs = new FileStream(@"D:\\RE", FileMode.Append);
        //        ViewBag.CategoryID = new SelectList(db.CATEGORies, "ID", "Name", title.CategoryID);
        //        return RedirectToAction("Index");

        //    }



        //    return View(title);

        //}

        // GET: Titles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Title title = db.Titles.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.CATEGORies, "ID", "Name", title.CategoryID);
            return View(title);
        }

        // POST: Titles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,CategoryID")] Title title)
        {
            if (ModelState.IsValid)
            {
                db.Entry(title).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.CATEGORies, "ID", "Name", title.CategoryID);
            return View(title);
        }

        // GET: Titles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Title title = db.Titles.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }

        // POST: Titles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Title title = db.Titles.Find(id);
            db.Titles.Remove(title);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SwirlsORS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@rendersection("scripts", required: false)*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.Stores, "Index", "Stores", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Products", "Index", "Stores")</li>
                    <li>@Html.ActionLink("Products List", "ListItem", "Stores")</li>
                    <li>@Html.ActionLink("List as Thumb Nails", "ListItem_t", "Stores")</li>
                    <li>@Html.ActionLink("Add Products", "AddItem", "Stores")</li>
                    <li>@Html.ActionLink("Forum", "Index", "Titles")</li>
                    <li>@Html.ActionLink("Add Title", "Create", "Titles")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
          
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>


              
</body>
</html>

SwirlsORS/Views/Shared/_LayoutPageNav.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title Vertical Menu</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-left navigation-list">
        @*<div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>*@
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Products", "Index", "Stores")</li>
                    <li>@Html.ActionLink("List Items", "ListItem", "Stores")</li>
                    <li>@Html.ActionLink("List Thumb Items", "ListItem_t", "Stores")</li>
                    <li>@Html.ActionLink("Add Items", "AddItem", "Stores")</li>
                </ul>
                @Html.Partial("_LoginPartial")
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@RenderSection("scripts", required: false)*@
</body>
</html>